apiVersion: v1
kind: Template
objects:

################################################################################
#
# OPERATOR
#
################################################################################

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: ${NAME}
    labels:
      app.plicity.io/name: ${NAME}

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      app.plicity.io/name: ${NAME}

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ${NAME}
    labels:
      app.plicity.io/name: ${NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${NAME}

- kind: Secret
  apiVersion: v1
  type: Opaque
  metadata:
    name: ${NAME}-gitlab-token
    labels:
      app.plicity.io/name: ${NAME}
  stringData:
    token: ${GITLAB_TOKEN}

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${NAME}-gitlab-config
    labels:
      app.plicity.io/name: ${NAME}
  data:
    url: ${GITLAB_REPOSITORY_URL}
    host: ${GITLAB_HOST}
    projectId: ${GITLAB_PROJECT_ID}

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${NAME}-config
    labels:
      app.plicity.io/name: ${NAME}
  data:
    name: ${NAME}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      app.plicity.io/name: ${NAME}
  spec:
    runPolicy: Serial
    triggers:
    - type: ImageChange
    - type: ConfigChange
    source:
      git:
        uri: ${GITLAB_REPOSITORY_URL}
      contextDir: ${DOCKERFILE_DIR}
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.plicity.io/name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
          app.plicity.io/name: ${NAME}
      spec:
        containers:
        - name: ${NAME}
          image: ${NAME}:latest
          ports:
          - containerPort: ${{PORT}}
            protocol: TCP
          env:
          - name: PLICITY_NAME
            value: ${NAME}
          - name: PLICITY_OPENSHIFT_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PLICITY_GITLAB_HOST
            valueFrom:
              configMapKeyRef:
                name: ${NAME}-gitlab-config
                key: host
          - name: PLICITY_GITLAB_URL
            valueFrom:
              configMapKeyRef:
                name: ${NAME}-gitlab-config
                key: url
          - name: PLICITY_GITLAB_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: ${NAME}-gitlab-config
                key: projectId
          - name: PLICITY_GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: ${NAME}-gitlab-token
                key: token
          - name: PLICITY_PORT
            value: "${PORT}"
        serviceAccountName: ${NAME}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - ${NAME}
          from:
            kind: ImageStreamTag
            name: ${NAME}:latest

- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.plicity.io/name: ${NAME}
  spec:
    ports:
    - port: ${{PORT}}
      protocol: TCP
      targetPort: ${{PORT}}
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP

- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
      app.plicity.io/name: ${NAME}
  spec:
    port:
      targetPort: ${{PORT}}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${NAME}-deployedbranches
    labels:
      app.plicity.io/name: ${NAME}

################################################################################
#
# PARAMETERS
#
################################################################################

parameters:

- name: GITLAB_REPOSITORY_URL
  required: true
- name: GITLAB_PROJECT_ID
  required: true
- name: GITLAB_HOST
  required: true
- name: GITLAB_TOKEN
  required: true
- name: NAME
  required: true
- name: PORT
  required: true
  value: "3000"
- name: DOCKERFILE_DIR
  required: true